app:
  scheduler:
    enable: true
    interval: 15s
    force-check-delay: 30s
  stackoverflowBaseUrl: https://api.stackexchange.com/2.3
  githubBaseUrl: https://api.github.com
  botBaseUrl: ${BOT_BASE_URL}
  githubAccessToken: ${GIT_HUB_ACCESS_TOKEN}

spring:
  application:
    name: scrapper
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
